Adds GitHub Actions
Studiosity/carmen-rails pull request #10
Opened 2023-04-05 10:22 UTC by yuri-zubov

2023-04-12 07:47 UTC, yuri-zubov commented
@abrom what do think about this PR?

2023-04-21 00:18 UTC, abrom requested changes
A few things that will need to be tidied up, but otherwise looks good. Thanks @yuri-zubov

2023-04-21 00:18 UTC, abrom commented on .github/workflows/ruby.yml
> +    name: Build + Publish
Should be just `Build`. 
```suggestion
    name: Build
```

2023-04-21 00:18 UTC, abrom commented on .github/workflows/ruby.yml
> +      packages: write
This should be removed.

2023-04-21 00:18 UTC, abrom commented on .github/workflows/ruby.yml
> +        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
Not sure why you're pegging this to v1.127.0? Latest using `ruby/setup-ruby@v1` would be v1.146.0
```suggestion
        uses: ruby/setup-ruby@v1
```

2023-04-28 06:53 UTC, yuri-zubov commented
@abrom I fixed your comments! Recheck again, please

2023-05-12 13:36 UTC, abrom approved these changes
Looks good @yuri-zubov thanks!

2023-05-12 13:36 UTC, merged